### ISSUE TITLE
BEM-loader for postcss

### ISSUE THREAD

**Issue by kovchiy** [bem/bem-react-core#95]
If I want to use css-globals or shared block styles I have to write this:

```css
/* NavBar-Item.css */

@import '../Globals/Globals.css';
@import '../NavBar-Vars.css';

.NavBar-Item {
    background: $color-brand;
    width: $navbar-width;
}
```

But I think this would be better:

```css
/* NavBar-Item.css */

@import 'b:Globals';
@import 'b:NavBar-Vars';

.NavBar-Item {
    background: $color-brand;
    width: $navbar-width;
}
```
